### PR TITLE
Add flatpak installation

### PR DESCRIPTION
**Pull request by CohenAriel**

### CODE REVIEW

**Comment by Shatur** [comment]
Thank you! Could you add the same for other languages?

**Comment by gasinvein** [comment]
@Shatur we can add "Get it on Flathub" badge if you'd like. Like this one:
```markdown
[![Download on Flathub](https://flathub.org/assets/badges/flathub-badge-en.svg)](https://flathub.org/apps/details/io.crow_translate.CrowTranslate)
```
[Download on Flathub](https://flathub.org/apps/details/io.crow_translate.CrowTranslate)
The URL on the badge also provides instructions on how to install it, so those become redundant in the readme.

**Comment by Shatur** [comment]
Looks nice!

**Comment by CohenAriel** [comment]
Sorry, didn't see there were other languages

**Pull request merged**
